### ISSUE TITLE
トップページの作成

### ISSUE THREAD

**Issue by Yuma-Satake** [nkc-ug/nkc_cloud#1]
##トップページ
- ログイン
- アカウント
- アップロードボタン
- about

**Comment by Yuma-Satake** [comment]
トップページこんな感じでどう？
<img width="1175" alt="スクリーンショット 2022-12-04 1 36 25" src="https://user-images.githubusercontent.com/109256327/205451570-21c002c5-d929-4ea0-8f43-aae680764ddd.png">

**Comment by yu-za66** [comment]
画面の配置綺麗で見やすいと思う
すげえ
