### ISSUE TITLE
APIドキュメントの追加

### ISSUE THREAD

**Issue by Yuma-Satake** [nkc-ug/nkc_cloud#2]
## 作業
- API・データ構造設計
- APIドキュメントの作成

**Comment by Yuma-Satake** [comment]
- ブランチは`feature/APIdoc`を作成済み
- `README`に`api.md`へのリンクを追記
- `doc`のディレクトリと`api.md`を追加

**Comment by raiden314** [comment]
・APIドキュメント完成しました
・プルリクを行う

**Comment by Yuma-Satake** [comment]
## ユーザごとの投稿一覧API
- 投稿一覧を表示したい場合に`記事のタイトル`も表示できる方がいいかも
- `ログインしているユーザのid`/`名前`はフロント側で保持するからデータとして持たなくて大丈夫◯

**Comment by Yuma-Satake** [comment]
## 会員登録API
- `ユーザid`フロントで管理できないから、サーバ側で生成
- `作成時刻`/`最終変更時間`は初回との記録はサーバ側に届いたタイミングの方が同期が取れて良さそう

**Comment by Yuma-Satake** [comment]
## 会員情報更新API
- `作成時刻`/`最終変更時刻`はサーバー側で変更にした方が同期が取れそう

**Comment by Yuma-Satake** [comment]
## ダウンロードする際の内容確認API
- `タイトル`も表示できるといいかも

**Comment by Yuma-Satake** [comment]
## ダウンロード API
- APIの形に関して、ダウンロードする際にサーバ側に送らなきゃいけない要素は`URL`/`パスワード`だと思うから`/api/v1/posts/{url}/{key}/download`
 が最低でも必要になるかな
- あと`パスワード`がないものに関してアクセスするときに、APIを使い分けないのであればそこに何を格納するかだな`0000`とかでもいいし、頼むわ

```
GET /api/v1/posts/{url}/download
```
|param|type|description|
|---|---|---|
|url|string|ダウンロードしたい記事のurl|
|title|string|ダウンロードしたい記事のタイトル|
|comment|tring|ダウンロードしたい記事のコメント|
|key|string|ダウンロードしたい記事のパスワード|
|date|date|ダウンロードしたい記事の有効期限|

**Comment by raiden314** [comment]
* レビューで明らかになった問題点を修正完了

**Comment by raiden314** [comment]
completed api.md

**Comment by raiden314** [comment]
ファイルの名前のカラムをアップロード　APIと選択した投稿の編集 APIに追加しました。
